name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            ctest --test-dir build -C Release --output-on-failure
          else
            ctest --test-dir build --output-on-failure
          fi
        shell: bash

      - name: Run benchmark (smoke)
        run: |
          cmake -E env CUBE96_BENCH_BYTES=65536 ./build/cube96_bench
        shell: bash
        if: matrix.os != 'windows-latest'

      - name: Run benchmark (smoke, Windows)
        run: |
          cmake -E env CUBE96_BENCH_BYTES=65536 build/Release/cube96_bench.exe
        if: matrix.os == 'windows-latest'
